# Generated by AtcoderGreedy on 2018-05-12
# ARC097 C
# Your code here

require 'set'

def read_inputs
  s = gets.chomp
  k = gets.chomp.to_i
  [s, k]
end

def read_example2
  s = 'atcoderandatcodeer'
  k = 5
  [s, k]
end

s, K = read_inputs

ordered = SortedSet.new
s.size.times do |l|
  (0..(s.size - 1 - l)).each do |i|
    ordered.add(s[i...(i + l + 1)])
  end
end

ordered.each.with_index do |e, i|
  if i == K - 1
    puts e
    break
  end
end
