---
:name: code-festival-2017-qualb
:date: 2017-10-08
:url: https://code-festival-2017-qualb.contest.atcoder.jp/
:task:
  :A:
    :id: '3572'
  :B:
    :id: '3573'
  :C:
    :id: '3574'
  :D:
    :id: '3575'
  :E:
    :id: '3576'
  :F:
    :id: '3577'
