# Generated by AtcoderGreedy on 2018-05-26
# ARC098 C
# Your code here

N = gets.chomp.to_i
S = gets.chomp

[:left, :right].map { |d| [d, {left: 0, right: 0}] }.to_h

acc = {
  left: Array.new(N+1),
  right: Array.new(N+1)
}

acc[:left][0] = { left: 0, right: 0 }
acc[:right][N] = { left: 0, right: 0 }

N.times do |i|
  if S[i] == 'W'
    acc[:left][i + 1] = { left: acc[:left][i][:left] + 1, right: acc[:left][i][:right] }
  else
    acc[:left][i + 1] = { left: acc[:left][i][:left], right: acc[:left][i][:right] + 1 }
  end
  if S[N - i - 1] == 'W'
    acc[:right][N - i - 1] = { left: acc[:right][N - i][:left] + 1, right: acc[:right][N - i][:right] }
  else
    acc[:right][N - i - 1] = { left: acc[:right][N - i][:left], right: acc[:right][N - i][:right] + 1 }
  end
end

mins = (0...N).map do |i|
  acc[:left][i][:left] + acc[:right][i + 1][:right]
end

puts mins.min
