# Generated by AtcoderGreedy on 2018-04-21
# ARC094 C
# Your code here

nums = gets.chomp.split(' ').map(&:to_i)

nums.sort!

biggest = nums.last
missings = nums[0..1].map { |i| biggest - i }.reduce(&:+)

ops = missings/2
residue = missings % 2
ops += 2 unless residue.zero?

puts ops
