---
:name: code-thanks-festival-2017-open
:date: 2017-12-02
:url: https://code-thanks-festival-2017-open.contest.atcoder.jp/
:task:
  :A:
    :id: '3636'
  :B:
    :id: '3637'
  :C:
    :id: '3638'
  :D:
    :id: '3639'
  :E:
    :id: '3640'
  :F:
    :id: '3641'
  :G:
    :id: '3642'
  :H:
    :id: '3643'
