# Generated by AtcoderGreedy on 2018-04-22
# CODE-THANKS-FESTIVAL-2017-OPEN B
# Your code here

$S = gets.chomp
length = $S.length
(0..length).each do |i|
  next unless $S[i..-1] == ($S[i..-1].reverse)
  puts i
  break
end
