---
:name: tdpc
:date: 2013-08-31
:url: https://tdpc.contest.atcoder.jp
:task:
  :A:
    :id: '679'
  :B:
    :id: '680'
  :C:
    :id: '682'
  :D:
    :id: '684'
  :E:
    :id: '681'
  :F:
    :id: '685'
  :G:
    :id: '686'
  :H:
    :id: '683'
  :I:
    :id: '688'
  :J:
    :id: '687'
  :K:
    :id: '691'
  :L:
    :id: '689'
  :M:
    :id: '694'
  :N:
    :id: '690'
  :O:
    :id: '693'
  :P:
    :id: '692'
  :Q:
    :id: '698'
  :R:
    :id: '696'
  :S:
    :id: '695'
  :T:
    :id: '697'
