#!/usr/bin/env ruby

# Generated by AtcoderGreedy on 2018-06-02
# BITFLYER2018-QUAL C

# my lib

module Enumerable
  # work just like String#split,
  # except this method does not use regex match
  # but check whether yield succeeds or not.
  def split
    current = nil
    ret = []
    each do |elem|
      if yield elem
        if current
          ret << current
          current = nil
        end
      elsif current
        current << elem
      else
        current = [elem]
      end
    end
    ret << current if current
    ret
  end
end

class Array
  # truncate tail, opposite of drop
  def clip(amount = 1)
    take_amount = size - amount
    take_amount < 0 ? [] : take(take_amount)
  end
end

# end of lib

# Your code here

N, D = gets.chomp.split(' ').map(&:to_i)
X = gets.chomp.split(' ').map(&:to_i)

ret = 0

(0...(N - 2)).each do |i|
  k = i + 2
  loop do
    k += 1 while k < N && X[k] - X[i] <= D
    break if k == N
    ((i + 1)...k).each do |j|
      next if X[k] - X[j] > D
      break if X[j] - X[i] > D
      ret += 1
    end
    k += 1
  end
end

puts ret
