# Generated by AtcoderGreedy on 2018-05-20
# AGC024 B
# Your code here

N = gets.chomp.to_i

arr = []
N.times do
  arr << gets.chomp.to_i
end

h = {}
arr.each do |n|
  if h.key?(n - 1)
    s = h.delete(n - 1)
    h[n] = s + 1
  else
    h[n] = 1
  end
end

puts(arr.size - h.values.max)
