# Generated by AtcoderGreedy on 2018-05-20
# AGC024 C
# Your code here

N = gets.chomp.to_i

arr = []
N.times do
  arr << gets.chomp.to_i
end

if arr[0] != 0
  puts(-1)
  exit 0
end

ops = 0
prev = 0
arr.drop(1).each do |a|
  succ_prev = prev + 1
  if succ_prev < a
    puts(-1)
    exit 0
  end
  ops += succ_prev != a ? a : 1
  prev = a
end

puts ops
