---
:name: agc025
:date: 2018-06-03
:url: https://agc025.contest.atcoder.jp
:task:
  :A:
    :id: '3964'
  :B:
    :id: '3965'
  :C:
    :id: '3966'
  :D:
    :id: '3967'
  :E:
    :id: '3968'
  :F:
    :id: '3969'
