---
:name: bitflyer2018-qual
:date: 2018-06-02
:url: https://bitflyer2018-qual.contest.atcoder.jp/
:task:
  :A:
    :id: '4145'
  :B:
    :id: '4146'
  :C:
    :id: '4147'
  :D:
    :id: '4148'
  :E:
    :id: '4149'
